"use client"

import { useRef, useState } from "react"
import { useRouter } from "next/navigation"
import { format } from "date-fns"
import { Cloud, Download, RefreshCw, Trash2, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useToast } from "@/components/ui/toast"
import { useLanguage } from "@/lib/i18n/LanguageContext"
import { ALLOWED_ETR_TYPES, MAX_DOCUMENT_SIZE } from "@/lib/constants"
import type { InvoiceDropboxDocumentItem } from "@/lib/data/invoices"

interface InvoiceEtrCardProps {
  invoiceId: string
  doc: InvoiceDropboxDocumentItem | undefined
  canManage: boolean
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

async function uploadEtr(invoiceId: string, file: File) {
  const formData = new FormData()
  formData.set("file", file)
  const res = await fetch(`/api/quotations/invoices/${invoiceId}/etr`, { method: "POST", body: formData })
  const body = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(body.error ?? "Failed to upload ETR")
  return body.document as { id: string }
}

async function deleteEtr(invoiceId: string) {
  const res = await fetch(`/api/quotations/invoices/${invoiceId}/etr`, { method: "DELETE" })
  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error(body.error ?? "Failed to delete ETR")
  }
}

/**
 * Invoice Detail's "ETR Tax Invoice" card — a single-slot upload/replace/
 * delete control for the user-uploaded eTIMS/ETR tax receipt, kept separate
 * from the system-generated "Dropbox Files" (PDF/XLSX) card since ETR has
 * no versioning and is never regenerated by the app.
 */
export function InvoiceEtrCard({ invoiceId, doc, canManage }: InvoiceEtrCardProps) {
  const router = useRouter()
  const toast = useToast()
  const { t } = useLanguage()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [busy, setBusy] = useState(false)
  const [confirmingDelete, setConfirmingDelete] = useState(false)

  function pickFile() {
    fileInputRef.current?.click()
  }

  async function handleFileChosen() {
    const file = fileInputRef.current?.files?.[0]
    if (!file) return
    if (!ALLOWED_ETR_TYPES.includes(file.type)) {
      toast.error(t("etrTypeNotAllowed"))
      if (fileInputRef.current) fileInputRef.current.value = ""
      return
    }
    if (file.size > MAX_DOCUMENT_SIZE) {
      toast.error(t("documentTooLarge"))
      if (fileInputRef.current) fileInputRef.current.value = ""
      return
    }

    setBusy(true)
    try {
      await uploadEtr(invoiceId, file)
      toast.success(t("documentUploaded"))
      router.refresh()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : t("etrUploadFailed"))
    } finally {
      setBusy(false)
      if (fileInputRef.current) fileInputRef.current.value = ""
    }
  }

  async function handleDelete() {
    if (!confirmingDelete) {
      setConfirmingDelete(true)
      return
    }
    setBusy(true)
    try {
      await deleteEtr(invoiceId)
      toast.success(t("documentDeleted"))
      router.refresh()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : t("documentDeleteFailed"))
    } finally {
      setBusy(false)
      setConfirmingDelete(false)
    }
  }

  const downloadUrl = `/api/quotations/invoices/${invoiceId}/documents/etr`

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5">
      <h3 className="text-sm font-semibold text-slate-900 mb-3 flex items-center gap-2">
        <Cloud className="h-4 w-4 text-slate-400" />
        {t("etrTaxInvoice")}
      </h3>

      <input
        ref={fileInputRef}
        type="file"
        className="hidden"
        accept={ALLOWED_ETR_TYPES.join(",")}
        onChange={handleFileChosen}
      />

      {doc ? (
        <div className="space-y-2 text-sm">
          <p className="truncate text-xs font-medium text-slate-900">{doc.dropboxFileName ?? "—"}</p>
          {doc.originalFileName && doc.originalFileName !== doc.dropboxFileName && (
            <p className="truncate text-xs text-slate-500">
              {t("originalLabel")}: {doc.originalFileName}
            </p>
          )}
          <p className="truncate font-mono text-[10px] text-slate-400">{doc.dropboxPath ?? "—"}</p>
          <p className="text-[11px] text-slate-400">
            {format(new Date(doc.createdAt), "dd MMM yyyy")} · {formatFileSize(doc.fileSize)}
          </p>

          <div className="flex flex-wrap items-center gap-2 pt-1">
            <a href={downloadUrl} target="_blank" rel="noopener noreferrer">
              <Button type="button" variant="outline" size="sm" icon={<Download className="h-3.5 w-3.5" />}>
                {t("download")}
              </Button>
            </a>
            {canManage && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                icon={<RefreshCw className="h-3.5 w-3.5" />}
                loading={busy && !confirmingDelete}
                onClick={pickFile}
              >
                {t("replace")}
              </Button>
            )}
            {canManage && (
              confirmingDelete ? (
                <div className="flex items-center gap-2 text-xs">
                  <span className="text-slate-500">{t("confirmDeleteEtr")}</span>
                  <button type="button" className="font-medium text-red-600 underline" onClick={handleDelete}>
                    {t("delete")}
                  </button>
                  <button type="button" className="text-slate-500" onClick={() => setConfirmingDelete(false)}>
                    {t("cancel")}
                  </button>
                </div>
              ) : (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  icon={<Trash2 className="h-3.5 w-3.5" />}
                  loading={busy && confirmingDelete}
                  onClick={handleDelete}
                >
                  {t("delete")}
                </Button>
              )
            )}
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          <p className="text-sm text-slate-400 italic">{t("documentNotUploaded")}</p>
          {canManage && (
            <Button
              type="button"
              variant="outline"
              size="sm"
              icon={<Upload className="h-3.5 w-3.5" />}
              loading={busy}
              onClick={pickFile}
            >
              {t("uploadFile")}
            </Button>
          )}
        </div>
      )}
    </div>
  )
}
